### PR TITLE
Added closed PR #5

### PR DESCRIPTION
**Pull request by landsman**
See more in original PR: https://github.com/BurdaMagazinOrg/thunder-project/pull/5

### CODE REVIEW

**Comment by landsman** [comment]
I was found strange behavior, about `oomphinc/composer-installers-extender` probably.

For first `composer install` (without any vendor downloaded yet) library not will moved to library folder. After second `composer install` will be moved to right path. 

@fago do you not have this problem with it?

here is more:
https://github.com/oomphinc/composer-installers-extender/issues/6

**Comment by dbosen** [comment]
@landsman I think this only works on first run, if the distribution also uses composer-installer-extenders, please try the 2.x branch of thunder-project to verify this.
But be aware, that this will build the beta version of thunder 2.

**Comment by landsman** [comment]
@dbosen first run is my problem right now. I must run composer twice for correct library folder.

**Comment by dbosen** [comment]
yes, I know.

**Review by dbosen — COMMENTED** [review]
Please use branch 2.x instead. We have made the changes there

**Comment by landsman** [comment]
Ok, I'll send it.

**Pull request closed without merging**
