### PR TITLE
Feature deploy themes

### PR DESCRIPTION
**Pull request by landsman**
Make theme deployment great again!

Example:
snimek obrazovky 2017-02-14 v 16 55 28

### CODE REVIEW

**Comment by tjwelde** [comment]
Looks nice.
I think we should add the node_modules directory to .gitignore, though.

**Comment by landsman** [comment]
Thank you!  They are prepared in another PR: https://github.com/BurdaMagazinOrg/infinite-theme/pull/41/files#diff-a084b794bc0759e7a6b77810e01874f2R48

**Comment by landsman** [comment]
I don't know why deployLibrares says `... undefined postinstall ...` if bower call update (bower libs already exists). Do you know why it show this message after second start of `bower install` @goldquest ?

**Comment by landsman** [comment]
I was add next method for deleting node_modules after deployment.
It's quicker for sending the CI's production server. Do you think that this should be in the core?

**composer.json**
```
    "scripts": {
        "dependency-cleanup": [
            "Thunder\\composer\\ScriptHandler::dependencyCleanup"
        ],
        "drupal-scaffold": "Thunder\\DrupalScaffold\\Plugin::scaffold",
        "post-install-cmd": [
            "Thunder\\composer\\ScriptHandler::buildScaffold",
            "Thunder\\composer\\ScriptHandler::createRequiredFiles",
            "Thunder\\composer\\ScriptHandler::deployLibraries",
            "Thunder\\composer\\ScriptHandler::deployThemes",
            "Thunder\\composer\\ScriptHandler::clearThemeDeploymentTools"
        ],
        "post-update-cmd": [
            "Thunder\\composer\\ScriptHandler::buildScaffold",
            "Thunder\\composer\\ScriptHandler::createRequiredFiles",
            "Thunder\\composer\\ScriptHandler::deployLibraries",
            "Thunder\\composer\\ScriptHandler::deployThemes",
            "Thunder\\composer\\ScriptHandler::clearThemeDeploymentTools"
        ]
    },
```

**ScriptHandler.php**
```
  /**
   * BurdaPraha custom function
   * @return array
   */
  public static function findNpmThemes() {
    $finder = new Finder();
    $folders = $finder
        ->files()
        ->in(static::getDrupalRoot(getcwd()) . "/themes")
        ->depth('2');

    $themes = array();
    foreach ($folders as $key => $item) {

      if (preg_match('/package.json$/', $item->getRelativePathname()))
      {
        $themes[] = str_replace('/package.json', '', $item->getRelativePathname());
      }

    }

    return $themes;
  }

  /**
   * BurdaPraha custom function
   * Install development dependencies for custom theme and run build tasker job
   * @param \Composer\Script\Event $event
   */
  public static function deployThemes(Event $event){

    $themes = self::findNpmThemes();
    $output = new ConsoleOutput();
    $table  = new Table($output);

    $table->setHeaders(array("Themes based on npm"));
    foreach($themes as $item)
    {
      $table->addRow(array($item));
    }
    if(count($themes) > 0) $table->render();

    $executor = new ProcessExecutor($event->getIO());
    foreach($themes as $theme) {
      $outputEvent = null;
      $event->getIO()->write('>> Started install assets for theme: ' . $theme);
      $executor->execute('npm install', $outputEvent, 'docroot/themes/' . $theme);
      $event->getIO()->write($outputEvent);
    }
  }

  /**
   * BurdaPraha custom function
   * @param Event $event
   */
  public static function clearThemeDeploymentTools(Event $event){

    $outputEvent = null;
    $executor = new ProcessExecutor($event->getIO());
    $themes = self::findNpmThemes();
    foreach($themes as $theme)
    {
        $finder = new Finder();
        $folders = $finder
            ->directories()
            ->in(static::getDrupalRoot(getcwd()) . '/themes/' . $theme)
            ->depth('0');

        foreach($folders as $folder)
        {
          if (preg_match('/node_modules/', $folder->getRelativePathname()))
          {
            $event->getIO()->write('>> Removing deployment tools in: ' . $theme);
            if($executor->execute('rm -rf ' . $folder, $outputEvent, $theme))
            {
              $event->getIO()->write('>> Removed: ' . $folder->getRelativePathname());
            }

          }
        }
    }
    $event->getIO()->write($outputEvent);
  }
```

Folder `node_modules` can be big and I'll send every build to production server via SSH as is and without this (not for production use) is it quicker.

What do you think?

**Pull request closed without merging**
